taskForge/projects/urls.py
from django.urls import path, include

from .views import ProjectDetailView, ProjectCreateView, ProjectListView, ProjectUpdateView, ProjectDeleteView

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('<int:pk>/', include([
        path('', ProjectDetailView.as_view(), name='details'),
        path('edit/', ProjectUpdateView.as_view(), name='edit'),
        path('delete/', ProjectDeleteView.as_view(), name='delete')
    ]))
]

taskForge/tickets/urls.py
from django.urls import path, include
from .views import (
    TicketListView,
    TicketDetailView,
    TicketCreateView,
    TicketUpdateView, TicketDeleteView, BugReportCreateView, BugReportApproveView, BugReportDenyView,
    BugReportDetailView
)

app_name = 'tickets'

urlpatterns = [
    path('', TicketListView.as_view(), name='list'),
    path('create/', TicketCreateView.as_view(), name='create'),
    path('<int:pk>/', include([
        path('', TicketDetailView.as_view(), name='details'),
        path('edit/', TicketUpdateView.as_view(), name='edit'),
        path('delete/', TicketDeleteView.as_view(), name='delete')
    ])),
    path('report-bug/', BugReportCreateView.as_view(), name='report-bug'),
    path('bugs/<int:pk>', include([
        path('approve/', BugReportApproveView.as_view(), name='approve-bug'),
        path('deny/', BugReportDenyView.as_view(), name='deny-bug'),
        path('', BugReportDetailView.as_view(), name='bug-details')
    ]))
]

taskForge/urls.py
from django.contrib import admin
from django.urls import path, include

from taskForge.views import Index, AboutView, ContactView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('accounts/', include('taskForge.accounts.urls')),
    path('projects/', include('taskForge.projects.urls')),
    path('tickets/', include('taskForge.tickets.urls')),
    path('comments/', include('taskForge.comments.urls'))
]

taskForge/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.dispatch import receiver

from taskForge.accounts.choices import UserRoleChoices


class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        if not email or not password:
            raise ValidationError('Email and password are required')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            username=email
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, first_name, last_name, password=None):
        user = self.create_user(email, first_name, last_name, password)
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=150, unique=True)

    objects = CustomUserManager()

    # USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [
        'first_name',
        'last_name'
    ]

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        swappable = 'AUTH_USER_MODEL'


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    role = models.CharField(
        max_length=20,
        choices=UserRoleChoices,
        default='end_user'
    )

    def __str__(self):
        return f'{self.user.first_name}\'s Profile'

taskForge/projects/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Project(models.Model):
    name = models.CharField(
        max_length=255,
    )
    description = models.TextField()
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='created_projects'
    )
    members = models.ManyToManyField(
        User,
        related_name='projects'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    lead_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='led_projects'
    )

    def __str__(self):
        return self.name

taskForge/tickets/models.py
from email.policy import default

from django.contrib.auth import get_user_model
from django.db import models

from taskForge.projects.models import Project
from taskForge.tickets.choices import TicketPriority, TicketStatus

User = get_user_model()


# Create your models here.
class BaseTicket(models.Model):
    title = models.CharField(
        max_length=200,
    )
    description = models.TextField()
    priority = models.CharField(
        max_length=30,
        choices=TicketPriority,
        default=TicketPriority.MEDIUM
    )
    status = models.CharField(
        max_length=30,
        choices=TicketStatus,
        default=TicketStatus.OPEN
    )
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='%(class)ss'
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='created_%(class)ss'
    )
    assigned_to = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='assigned_%(class)ss'
    )
    due_date = models.DateField(
        null=True,
        blank=True,
        help_text="Expected completion date"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        abstract=True
        ordering = ['-created_at']

    def __str__(self):
        return self.title

class Ticket(BaseTicket):
    is_bug_ticket = models.BooleanField(default=False)
    original_bug_report = models.OneToOneField(
        'BugReport',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='converted_ticket'
    )


class BugReport(BaseTicket):
    is_approved = models.BooleanField(default=False)

taskForge/projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils import timezone

from taskForge.accounts.choices import UserRoleChoices
from taskForge.projects.forms import ProjectForm
from taskForge.projects.models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    """
    Visible to all authenticated users that belong to the project
    Staff and Admin can see full list of the Projects, and can do full crud
    """
    model = Project
    template_name = 'projects/project-list.html'
    context_object_name = 'projects'

    def get_queryset(self):
        user = self.request.user

        if user.is_staff:
            return Project.objects.all()
        elif user.profile.role == UserRoleChoices.END_USER:
            return Project.objects.filter(members=user)
        else:
            return Project.objects.filter(members=user)


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class ProjectCreateView(LoginRequiredMixin, StaffRequiredMixin, CreateView):
    """
    Staff and Admin can do full crud
    This is invisible to lower users
    """
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project-creation.html'
    success_url = reverse_lazy('projects:list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProjectUpdateView(LoginRequiredMixin, StaffRequiredMixin, UpdateView):
    """
    Only staff and admin can do full crud
    """
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project-edit.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse_lazy('projects:details', kwargs={'pk': self.object.pk})


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('projects:list')

    def test_func(self):
        return self.request.user.is_staff

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        return result


class ProjectDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Project
    template_name = 'projects/project details/project-details.html'
    context_object_name = 'project'

    def test_func(self):
        project = self.get_object()
        user = self.request.user
        return user.is_staff or user in project.members.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        view_type = self.request.GET.get('view', 'summary')
        context['view_type'] = view_type
        context['now'] = timezone.now().date()

        sort_by = self.request.GET.get('sort', '-created_at')
        sort_direction = self.request.GET.get('direction', 'asc')

        context['current_sort'] = sort_by
        context['current_direction'] = sort_direction

        sort_field = f'-{sort_by}' if sort_direction == 'desc' else sort_by

        if view_type == 'board':
            context['tickets'] = self.object.tickets.exclude(
                status__in=['closed', 'resolved']
            ).order_by(sort_field)

            if self.request.user.is_staff:
                context['pending_bugs'] = self.object.bugreports.filter(
                    is_approved=False
                ).order_by(sort_field)

        elif view_type == 'archived':
            context['archived_tickets'] = self.object.tickets.filter(
                status__in=['closed', 'resolved']
            ).order_by(sort_field)

        context['is_end_user'] = self.request.user.profile.role == UserRoleChoices.END_USER
        return context

taskForge/projects/views/analytics_views.py
import asyncio

from asgiref.sync import sync_to_async
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from ..analytics.charts import (
    generate_priority_chart,
    generate_status_chart,
    generate_work_types_chart,
    generate_team_workload_chart,
)


class ProjectSummaryView(LoginRequiredMixin, DetailView):
    template_name = 'projects/project details/project-summary.html'

    async def get_context_data(self, **kwargs):
        context = await super().get_context_data(**kwargs)
        if context['view_type'] == 'summary':
            priority_chart = sync_to_async(generate_priority_chart)
            status_chart = sync_to_async(generate_status_chart)
            work_types_chart = sync_to_async(generate_work_types_chart)
            team_workload_chart = sync_to_async(generate_team_workload_chart)

            data = await asyncio.gather(
                priority_chart(self.object),
                status_chart(self.object),
                work_types_chart(self.object),
                team_workload_chart(self.object),
            )

            context.update({
                'priority_chart': data[0],
                'status_chart': data[1],
                'work_types_chart': data[2],
                'team_workload_chart': data[3],
            })

        return context

taskForge/projects/views/project_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils import timezone

from taskForge.accounts.choices import UserRoleChoices
from taskForge.projects.analytics.charts import (
    generate_priority_chart,
    generate_status_chart,
    generate_work_types_chart,
    generate_team_workload_chart
)
from taskForge.projects.forms import ProjectForm
from taskForge.projects.models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    """
    Visible to all authenticated users that belong to the project
    Staff and Admin can see full list of the Projects, and can do full crud
    """
    model = Project
    template_name = 'projects/project-list.html'
    context_object_name = 'projects'

    def get_queryset(self):
        user = self.request.user

        if user.is_staff:
            return Project.objects.all()
        elif user.profile.role == UserRoleChoices.END_USER:
            return Project.objects.filter(members=user)
        else:
            return Project.objects.filter(members=user)


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class ProjectCreateView(LoginRequiredMixin, StaffRequiredMixin, CreateView):
    """
    Staff and Admin can do full crud
    This is invisible to lower users
    """
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project-creation.html'
    success_url = reverse_lazy('projects:list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProjectUpdateView(LoginRequiredMixin, StaffRequiredMixin, UpdateView):
    """
    Only staff and admin can do full crud
    """
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project-edit.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_success_url(self):
        return reverse_lazy('projects:details', kwargs={'pk': self.object.pk})


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('projects:list')

    def test_func(self):
        return self.request.user.is_staff

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        return result


class ProjectDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Project
    template_name = 'projects/project details/project-details.html'
    context_object_name = 'project'

    def test_func(self):
        project = self.get_object()
        user = self.request.user
        return user.is_staff or user in project.members.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        view_type = self.request.GET.get('view', 'summary')
        context['view_type'] = view_type
        context['now'] = timezone.now().date()

        sort_by = self.request.GET.get('sort', '-created_at')
        sort_direction = self.request.GET.get('direction', 'asc')

        context['current_sort'] = sort_by
        context['current_direction'] = sort_direction

        sort_field = f'-{sort_by}' if sort_direction == 'desc' else sort_by

        if view_type == 'board':
            context['tickets'] = self.object.tickets.exclude(
                status__in=['closed', 'resolved']
            ).order_by(sort_field)

            if self.request.user.is_staff:
                context['pending_bugs'] = self.object.bugreports.filter(
                    is_approved=False
                ).order_by(sort_field)

        elif view_type == 'archived':
            context['archived_tickets'] = self.object.tickets.filter(
                status__in=['closed', 'resolved']
            ).order_by(sort_field)

        elif view_type == 'summary':
            try:
                from ..analytics.utils import calculate_project_stats
                context['project_stats'] = calculate_project_stats(self.object)

                context.update({
                    'priority_chart': generate_priority_chart(self.object),
                    'status_chart': generate_status_chart(self.object),
                    'work_types_chart': generate_work_types_chart(self.object),
                    'team_workload_chart': generate_team_workload_chart(self.object)
                })
            except Exception as e:
                print(f"Error generating analytics: {e}")
                context['analytics_error'] = "Unable to load analytics data"

        context['is_end_user'] = self.request.user.profile.role == UserRoleChoices.END_USER
        return context

templates/projects/project details/project-board.html
<div class="card shadow-sm">
    <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Project Board</h5>
        <div class="btn-group">
            {% if not user.profile.role == 'end_user' %}
                <a href="{% url 'tickets:create' %}?project={{ project.pk }}" class="btn btn-primary btn-sm me-2">
                    <i class="bi bi-plus-lg me-1"></i>Create Ticket
                </a>
            {% endif %}
            <a href="{% url 'tickets:report-bug' %}?project={{ project.pk }}" class="btn btn-outline-warning btn-sm">
                <i class="bi bi-bug me-1"></i>Report Bug
            </a>
        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead>
                <tr>
                    <th>
                        <a href="?view=board&sort=title&direction={% if current_sort == 'title' and current_direction == 'asc' %}desc{% else %}asc{% endif %}"
                           class="">
                            Title
                            {% if current_sort == 'title' %}
                                {% if current_direction == 'asc' %}
                                    <i class="bi bi-arrow-up-short"></i>
                                {% else %}
                                    <i class="bi bi-arrow-down-short"></i>
                                {% endif %}
                            {% endif %}
                        </a>
                    </th>
                    <th>Type</th>
                    <th>
                        <a href="?view=board&sort=status&direction={% if current_sort == 'status' and current_direction == 'asc' %}desc{% else %}asc{% endif %}"
                           class="">
                            Status
                            {% if current_sort == 'status' %}
                                {% if current_direction == 'asc' %}
                                    <i class="bi bi-arrow-up-short"></i>
                                {% else %}
                                    <i class="bi bi-arrow-down-short"></i>
                                {% endif %}
                            {% endif %}
                        </a>
                    </th>
                    <th>
                        <a href="?view=board&sort=priority&direction={% if current_sort == 'priority' and current_direction == 'asc' %}desc{% else %}asc{% endif %}"
                           class="">
                            Priority
                            {% if current_sort == 'priority' %}
                                {% if current_direction == 'asc' %}
                                    <i class="bi bi-arrow-up-short"></i>
                                {% else %}
                                    <i class="bi bi-arrow-down-short"></i>
                                {% endif %}
                            {% endif %}
                        </a>
                    </th>
                    <th>
                        <a href="?view=board&sort=assigned_to&direction={% if current_sort == 'assigned_to' and current_direction == 'asc' %}desc{% else %}asc{% endif %}"
                           class="">
                            Assigned To
                            {% if current_sort == 'assigned_to' %}
                                {% if current_direction == 'asc' %}
                                    <i class="bi bi-arrow-up-short"></i>
                                {% else %}
                                    <i class="bi bi-arrow-down-short"></i>
                                {% endif %}
                            {% endif %}
                        </a>
                    </th>
                    <th>
                        <a href="?view=board&sort=due_date&direction={% if current_sort == 'due_date' and current_direction == 'asc' %}desc{% else %}asc{% endif %}"
                           class="">
                            Due Date
                            {% if current_sort == 'due_date' %}
                                {% if current_direction == 'asc' %}
                                    <i class="bi bi-arrow-up-short"></i>
                                {% else %}
                                    <i class="bi bi-arrow-down-short"></i>
                                {% endif %}
                            {% endif %}
                        </a>
                    </th>
                    <th>
                        <a href="?view=board&sort=created_at&direction={% if current_sort == 'created_at' and current_direction == 'asc' %}desc{% else %}asc{% endif %}"
                           class="">
                            Created
                            {% if current_sort == 'created_at' %}
                                {% if current_direction == 'asc' %}
                                    <i class="bi bi-arrow-up-short"></i>
                                {% else %}
                                    <i class="bi bi-arrow-down-short"></i>
                                {% endif %}
                            {% endif %}
                        </a>
                    </th>
                </tr>
                </thead>
                <tbody>

                {% for bug in project.bugreports.all %}
                    {% if not bug.is_approved and bug.status != 'closed' and bug.status != 'resolved' %}
                        <tr>
                            <td>
                                <a href="{% url 'tickets:bug-details' bug.pk %}" class="text-decoration-none">
                                    <span class="badge bg-warning me-1">PENDING</span>
                                    {{ bug.title }}
                                </a>
                            </td>
                            <td>
                                <span class="text-warning">Bug Report</span>
                            </td>
                            <td>
                                <span class="badge bg-warning">Pending Review</span>
                            </td>
                            <td>
                                    <span class="badge {% if bug.priority == 'low' %}bg-success
                                                      {% elif bug.priority == 'medium' %}bg-warning
                                                      {% elif bug.priority == 'high' %}bg-danger
                                                      {% else %}bg-danger{% endif %}">
                                        {{ bug.get_priority_display }}
                                    </span>
                            </td>
                            <td>
                                <span class="text-muted">Pending</span>
                            </td>
                            <td>
                                <small class="text-muted">{{ bug.created_at|date:"M d, Y" }}</small>
                            </td>
                            <td class="text-end">
                                {% if user.is_staff %}
                                    <div class="btn-group">
                                        <form method="post" action="{% url 'tickets:approve-bug' bug.pk %}"
                                              class="d-inline">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-success btn-sm me-1">
                                                <i class="bi bi-check"></i>
                                            </button>
                                        </form>
                                        <form method="post" action="{% url 'tickets:deny-bug' bug.pk %}"
                                              class="d-inline">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger btn-sm">
                                                <i class="bi bi-x"></i>
                                            </button>
                                        </form>
                                    </div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                {% for ticket in tickets %}
                    {% if ticket.status != 'closed' and ticket.status != 'resolved' %}
                        <tr>
                            <td>
                                <a href="{% url 'tickets:details' ticket.pk %}" class="text-decoration-none">
                                    {% if ticket.is_bug_ticket %}
                                        <i class="bi bi-bug"></i>
                                    {% else %}
                                        <i class="bi bi-list-check"></i>
                                    {% endif %}
                                    {{ ticket.title }}
                                </a>
                            </td>
                            <td>
                                {% if ticket.is_bug_ticket %}
                                    <span class="text-danger">Bug Report</span>
                                {% else %}
                                    <span class="text-primary">Ticket</span>
                                {% endif %}
                            </td>
                            <td>
                                    <span class="badge {% if ticket.status == 'open' %}bg-secondary
                                                      {% elif ticket.status == 'in_progress' %}bg-primary
                                                      {% elif ticket.status == 'resolved' %}bg-success
                                                      {% else %}bg-dark{% endif %}">
                                        {{ ticket.get_status_display }}
                                    </span>
                            </td>
                            <td>
                                    <span class="badge {% if ticket.priority == 'low' %}bg-success
                                                      {% elif ticket.priority == 'medium' %}bg-warning
                                                      {% elif ticket.priority == 'high' %}bg-danger
                                                      {% else %}bg-danger{% endif %}">
                                        {{ ticket.get_priority_display }}
                                    </span>
                            </td>
                            <td>
                                {% if ticket.assigned_to %}
                                    {{ ticket.assigned_to.get_full_name }}
                                {% else %}
                                    <span class="text-muted">Unassigned</span>
                                {% endif %}
                            </td>

                            <td>
                                {% if ticket.due_date %}
                                    <small class="{% if ticket.due_date|date:'Y-m-d' < now|date:'Y-m-d' %}text-danger{% else %}text-muted{% endif %}">
                                        {{ ticket.due_date|date:"M d, Y" }}
                                    </small>
                                {% else %}
                                    <small class="text-muted">No deadline</small>
                                {% endif %}
                            </td>
                            <td>
                                <small class="text-muted">{{ ticket.created_at|date:"M d, Y H:i" }}</small>
                            </td>


                            <td class="text-end">
                                {% if user.is_staff or user == ticket.created_by or user == ticket.assigned_to %}
                                    <a href="{% url 'tickets:edit' ticket.pk %}" class="btn btn-outline-primary btn-sm">
                                        <i class="bi bi-pencil"></i>
                                    </a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}


                {% if not tickets.exists and not pending_bugs %}
                    <tr>
                        <td colspan="7" class="text-center text-muted py-4">
                            No active tickets or bug reports
                        </td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>